Repository pgbackrest/pgbackrest, pull requests merged in 2020-11, with the labels that each got.

#1221 Prepare configuration module for multi-repository support.
  build/lib/pgBackRestBuild/Config/Build.pm
  build/lib/pgBackRestBuild/Config/BuildDefine.pm
  build/lib/pgBackRestBuild/Config/BuildParse.pm
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  src/command/backup/backup.c
  src/command/check/check.c
  src/command/check/common.c
  src/command/command.c
  src/command/help/help.c
  src/common/type/stringz.h
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/config.c
  src/config/config.h
  src/config/config.intern.h
  src/config/define.auto.c
  src/config/define.auto.h
  src/config/define.c
  src/config/define.h
  src/config/exec.c
  src/config/load.c
  src/config/parse.auto.c
  src/config/parse.c
  src/config/parse.h
  src/config/protocol.c
  src/db/helper.c
  src/protocol/helper.c
  src/storage/helper.c
  src/storage/helper.h
  test/define.yaml
  test/src/common/harnessConfig.c
  test/src/module/command/localTest.c
  test/src/module/config/configTest.c
  test/src/module/config/defineTest.c
  test/src/module/config/loadTest.c
  test/src/module/config/parseTest.c
  test/src/module/db/dbTest.c
  test/src/module/protocol/protocolTest.c
Labels: enhancement, module [core]

#1235 Move retrieval of archiveResult before while loop in verifyArchive().
  src/command/verify/verify.c
Labels: enhancement

#1237 Create standby.signal only on PostgreSQL 12 when restore type is standby.
  doc/xml/release.xml
  src/command/restore/restore.c
  test/src/module/command/restoreTest.c
Labels: bug, module [core]

#1239 Allow multiple remote locks from the same main process.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/release.xml
  src/command/archive/get/get.c
  src/command/archive/push/push.c
  src/command/control/stop.c
  src/command/info/info.c
  src/command/remote/remote.c
  src/command/restore/restore.c
  src/common/lock.c
  src/common/lock.h
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/define.auto.c
  src/config/define.auto.h
  src/config/load.c
  src/config/parse.auto.c
  test/expect/mock-all-001.log
  test/expect/mock-all-002.log
  test/expect/mock-archive-001.log
  test/expect/mock-archive-002.log
  test/expect/mock-archive-stop-001.log
  test/expect/mock-archive-stop-002.log
  test/expect/mock-expire-001.log
  test/expect/mock-expire-002.log
  test/expect/mock-stanza-001.log
  test/expect/mock-stanza-002.log
  test/lib/pgBackRestTest/Common/LogTest.pm
  test/src/common/harnessConfig.c
  test/src/module/command/archiveGetTest.c
  test/src/module/command/archivePushTest.c
  test/src/module/command/commandTest.c
  test/src/module/command/controlTest.c
  test/src/module/command/infoTest.c
  test/src/module/common/exitTest.c
  test/src/module/common/lockTest.c
  test/src/module/config/execTest.c
  test/src/module/config/loadTest.c
  test/src/module/protocol/protocolTest.c
Labels: enhancement, module [core]

#1223 Report page checksum errors in info command text output.
  doc/xml/release.xml
  src/command/info/info.c
  test/src/module/command/infoTest.c
Labels: enhancement, module [core]
