Repository pgbackrest/pgbackrest, pull requests merged in 2020-08, with the labels that each got.

#1123 Improve memory usage of unlogged relation detection in manifest build.
  doc/xml/release.xml
  src/info/manifest.c
  test/lib/pgBackRestTest/Common/JobTest.pm
Labels: enhancement, module [core]

#1130 Proactively close file descriptors after forking async process.
  doc/xml/release.xml
  src/command/archive/common.c
Labels: enhancement, module [core]

#1131 Improve TLS error reporting.
  doc/xml/release.xml
  src/common/io/tls/session.c
  test/src/module/common/ioTlsTest.c
Labels: enhancement, module [core]

#1133 Move file descriptor read/write ready into IoRead/IoWrite.
  doc/xml/release.xml
  src/Makefile.in
  src/command/local/local.c
  src/command/remote/remote.c
  src/command/repo/get.c
  src/command/repo/ls.c
  src/common/exec.c
  src/common/io/fd.c
  src/common/io/fd.h
  src/common/io/fdRead.c
  src/common/io/fdWrite.c
  src/common/io/fdWrite.h
  src/common/io/read.c
  src/common/io/read.h
  src/common/io/read.intern.h
  src/common/io/socket/common.c
  src/common/io/socket/common.h
  src/common/io/socket/session.c
  src/common/io/socket/session.h
  src/common/io/tls/session.c
  src/common/io/write.c
  src/common/io/write.h
  src/common/io/write.intern.h
  test/define.yaml
  test/src/module/command/archivePushTest.c
  test/src/module/command/controlTest.c
  test/src/module/command/localTest.c
  test/src/module/command/remoteTest.c
  test/src/module/common/execTest.c
  test/src/module/common/ioHttpTest.c
  test/src/module/common/ioTest.c
  test/src/module/common/ioTlsTest.c
  test/src/module/config/protocolTest.c
  test/src/module/db/dbTest.c
  test/src/module/performance/storageTest.c
  test/src/module/protocol/protocolTest.c
  test/src/module/storage/azureTest.c
  test/src/module/storage/s3Test.c
Labels: enhancement, module [core]

#1134 Delay backup remote connection close until after archive check.
  doc/xml/release.xml
  src/command/backup/backup.c
Labels: enhancement, module [core]

#1135 Implement IoClient/IoSession interfaces for SocketClient/SocketSession.
  doc/xml/release.xml
  src/command/command.c
  src/common/io/client.c
  src/common/io/client.h
  src/common/io/client.intern.h
  src/common/io/session.c
  src/common/io/session.h
  src/common/io/session.intern.h
  src/common/io/socket/client.c
  src/common/io/socket/client.h
  src/common/io/socket/session.c
  src/common/io/socket/session.h
  src/common/io/tls/client.c
  src/common/io/tls/client.h
  src/common/io/tls/session.c
  src/common/io/tls/session.h
  src/storage/azure/storage.c
  src/storage/s3/storage.c
  test/src/common/harnessTls.c
  test/src/module/command/commandTest.c
  test/src/module/common/ioHttpTest.c
  test/src/module/common/ioTlsTest.c
  test/src/module/storage/s3Test.c
Labels: enhancement

#1140 Add missing azure type in repo-type option reference.
  doc/xml/reference.xml
  doc/xml/release.xml
  src/config/define.auto.c
Labels: bug, module [doc]

#1144 Add support for HTTP/1.0.
  doc/xml/release.xml
  src/common/io/http/request.c
  src/common/io/http/request.h
  src/common/io/http/response.c
  test/src/module/common/ioHttpTest.c
Labels: enhancement

#1150 Add user-agent to HTTP requests.
  doc/xml/release.xml
  src/common/io/http/request.c
  test/src/module/common/ioHttpTest.c
  test/src/module/storage/azureTest.c
  test/src/module/storage/s3Test.c
Labels: enhancement, module [core]

#1151 Asynchronous list/remove for S3/Azure storage.
  doc/xml/release.xml
  src/storage/azure/storage.c
  src/storage/s3/storage.c
Labels: enhancement, module [core]

#1152 Add general-purpose statistics collector.
  doc/xml/release.xml
  src/Makefile.in
  src/command/command.c
  src/common/io/http/client.c
  src/common/io/http/client.h
  src/common/io/http/request.c
  src/common/io/http/response.c
  src/common/io/socket/client.c
  src/common/io/socket/client.h
  src/common/io/tls/client.c
  src/common/io/tls/client.h
  src/common/stat.c
  src/common/stat.h
  src/main.c
  test/define.yaml
  test/expect/mock-all-002.log
  test/expect/mock-archive-002.log
  test/expect/mock-archive-stop-002.log
  test/expect/mock-stanza-002.log
  test/lib/pgBackRestTest/Common/LogTest.pm
  test/src/module/command/commandTest.c
  test/src/module/common/ioHttpTest.c
  test/src/module/common/ioTlsTest.c
  test/src/module/common/statTest.c
  test/src/module/performance/typeTest.c
  test/src/test.c
Labels: enhancement, module [core]

#1154 Improve detailed error output.
  doc/xml/release.xml
  src/common/exit.c
  test/src/module/common/exitTest.c
Labels: enhancement, module [core]

#1137 Automatically retrieve temporary S3 credentials on AWS instances.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/define.auto.c
  src/config/define.auto.h
  src/config/parse.auto.c
  src/storage/helper.c
  src/storage/s3/storage.c
  src/storage/s3/storage.h
  test/src/module/command/helpTest.c
  test/src/module/storage/s3Test.c
Labels: enhancement, module [core]

#1160 Add archive-mode option to disable archiving on restore.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/command/restore/restore.c
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/define.auto.c
  src/config/define.auto.h
  src/config/parse.auto.c
  test/src/module/command/helpTest.c
  test/src/module/command/restoreTest.c
Labels: enhancement, module [core]
