Repository pgbackrest/pgbackrest, pull requests merged in 2020-07, with the labels that each got.

#1091 Fix restore --force acting like --force --delta.
  doc/xml/release.xml
  src/command/restore/restore.c
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
  test/src/module/command/restoreTest.c
Labels: bug

#1093 Add shared access signature (SAS) authorization for Azure.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/define.auto.c
  src/config/define.auto.h
  src/config/parse.auto.c
  src/storage/azure/storage.c
  src/storage/azure/storage.h
  src/storage/helper.c
  test/src/module/command/helpTest.c
  test/src/module/storage/azureTest.c
Labels: enhancement

#1098 Add expire-auto option to the backup command
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/define.auto.c
  src/config/define.auto.h
  src/config/parse.auto.c
  src/main.c
  test/expect/real-all-001.log
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
Labels: enhancement, module [core]

#1105 Automatic retry for backup, restore, archive-get, and archive-push.
  doc/xml/release.xml
  src/command/local/local.c
  src/command/remote/remote.c
  src/protocol/server.c
  src/protocol/server.h
  src/storage/s3/storage.c
  test/src/module/command/archiveGetTest.c
  test/src/module/command/archivePushTest.c
  test/src/module/command/backupTest.c
  test/src/module/command/restoreTest.c
  test/src/module/config/protocolTest.c
  test/src/module/db/dbTest.c
  test/src/module/performance/storageTest.c
  test/src/module/protocol/protocolTest.c
  test/src/module/storage/s3Test.c
Labels: enhancement, module [core]

#1095 Automatically determine cipher passphrase in repo-get command.
  doc/xml/release.xml
  src/command/backup/backup.c
  src/command/backup/common.h
  src/command/repo/get.c
  test/src/module/command/repoTest.c
Labels: enhancement, module [core]

#1107 Remove real/all integration tests now covered by unit tests.
  doc/xml/release.xml
  test/expect/real-all-001.log
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
Labels: enhancement, module [test]

#1113 Add passing of storage to pgWalFromFile.
  src/command/archive/push/file.c
  src/postgres/interface.c
  src/postgres/interface.h
  test/src/module/postgres/interfaceTest.c
Labels: enhancement, module [core]

#1119 Suppress errors when closing local/remote processes.
  doc/xml/release.xml
  src/common/exit.c
  src/protocol/helper.c
  src/protocol/helper.h
  src/protocol/parallel.c
  test/define.yaml
  test/src/module/protocol/protocolTest.c
Labels: bug, module [core]

#1120 Fix issue with = character in file or database names.
  doc/xml/release.xml
  src/common/ini.c
  test/src/module/common/iniTest.c
  test/src/module/info/manifestTest.c
Labels: bug, module [core]

#1125 Preserve Variant parsed from JSON in iniLoad().
  doc/xml/release.xml
  src/common/ini.c
  src/common/ini.h
  src/info/info.c
  src/info/info.h
  src/info/infoBackup.c
  src/info/infoPg.c
  src/info/manifest.c
  test/src/common/harnessInfo.c
  test/src/common/harnessInfo.h
  test/src/module/common/iniTest.c
  test/src/module/performance/typeTest.c
Labels: enhancement, module [core]
