Repository pgbackrest/pgbackrest, pull requests merged in 2020-06, with the labels that each got.

#1067 Fix expression when recursion enabled in storageInfoListP().
  doc/xml/release.xml
  src/storage/storage.c
  test/src/module/storage/posixTest.c
Labels: enhancement, module [core]

#1068 Improve behavior of the repo-ls command.
  doc/xml/release.xml
  src/command/repo/ls.c
  test/src/module/command/repoTest.c
Labels: enhancement, module [core]

#1071 Update FAQ page for expiring a specific backup set.
  doc/xml/faq.xml
  doc/xml/release.xml
Labels: enhancement, module [doc]

#1072 Update the PITR FAQ to clarify the default behavior.
  doc/xml/faq.xml
  doc/xml/release.xml
Labels: enhancement

#1075 Add hint when checksum delta is enabled after a timeline switch.
  doc/xml/release.xml
  src/info/manifest.c
  test/src/module/command/backupTest.c
  test/src/module/info/manifestTest.c
Labels: enhancement, module [core]

#1076 Rename postmaster where possible.
  build/error.yaml
  doc/lib/pgBackRestDoc/Common/Exception.pm
  doc/xml/release.xml
  src/command/backup/backup.c
  src/command/restore/restore.c
  src/command/stanza/delete.c
  src/common/error.auto.c
  src/common/error.auto.h
  src/info/manifest.c
  test/expect/mock-all-001.log
  test/expect/mock-all-002.log
  test/expect/real-all-001.log
  test/lib/pgBackRestTest/Env/Host/HostDbTest.pm
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
  test/src/module/command/backupTest.c
  test/src/module/command/restoreTest.c
  test/src/module/command/stanzaTest.c
Labels: enhancement, module [core]

#1078 Inline strPtr() to increase profiling accuracy.
  doc/xml/release.xml
  src/common/io/tls/client.c
  src/common/type/string.c
  src/common/type/string.h
  test/src/common/harnessTest.h
  test/src/module/common/typeStringTest.c
Labels: enhancement, module [core]

#1079 Add strCatZ().
  src/command/backup/backup.c
  src/command/backup/common.c
  src/command/command.c
  src/command/help/help.c
  src/command/info/info.c
  src/command/restore/restore.c
  src/common/compress/helper.c
  src/common/exit.c
  src/common/io/http/header.c
  src/common/io/http/query.c
  src/common/type/buffer.c
  src/common/type/json.c
  src/common/type/string.c
  src/common/type/string.h
  src/common/type/stringList.c
  src/config/load.c
  src/config/parse.c
  src/db/db.c
  src/info/manifest.c
  src/protocol/client.c
  src/storage/s3/storage.c
  test/src/common/harnessLog.c
  test/src/common/harnessStorage.c
  test/src/module/command/backupTest.c
  test/src/module/command/expireTest.c
  test/src/module/common/typeStringTest.c
  test/src/module/config/parseTest.c
  test/src/module/performance/typeTest.c
  test/src/module/storage/s3Test.c
Labels: enhancement, module [core]

#1081 Asynchronous S3 multipart upload.
  doc/xml/release.xml
  src/Makefile.in
  src/command/repo/create.c
  src/common/io/http/cache.c
  src/common/io/http/client.c
  src/common/io/http/client.h
  src/common/io/http/query.c
  src/common/io/http/query.h
  src/common/io/http/request.c
  src/common/io/http/request.h
  src/common/io/http/response.c
  src/common/io/http/response.h
  src/common/io/http/session.c
  src/common/io/http/session.h
  src/storage/s3/read.c
  src/storage/s3/storage.c
  src/storage/s3/storage.intern.h
  src/storage/s3/write.c
  test/define.yaml
  test/expect/mock-stanza-002.log
  test/src/common/harnessTest.h
  test/src/module/common/ioHttpTest.c
  test/src/module/storage/s3Test.c
Labels: enhancement, module [core]

#1086 Disable query parallelism in PostgreSQL sessions used for backup control.
  doc/xml/release.xml
Labels: enhancement
