Repository pgbackrest/pgbackrest, pull requests merged in 2020-05, with the labels that each got.

#1025 Add bzip2 support
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/contributing.xml
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/Makefile.in
  src/build/configure.ac
  src/common/compress/bz2/common.c
  src/common/compress/bz2/common.h
  src/common/compress/bz2/compress.c
  src/common/compress/bz2/compress.h
  src/common/compress/bz2/decompress.c
  src/common/compress/bz2/decompress.h
  src/common/compress/helper.c
  src/common/compress/helper.h
  src/config/define.auto.c
  src/configure
  test/Vagrantfile
  test/container.yaml
  test/define.yaml
  test/lib/pgBackRestTest/Common/ContainerTest.pm
  test/lib/pgBackRestTest/Common/JobTest.pm
  test/lib/pgBackRestTest/Env/Host/HostBackupTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockAllTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockArchiveStopTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockArchiveTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockStanzaTest.pm
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
  test/patch/debian-package.patch
  test/src/module/common/compressTest.c
  test/travis.pl
Labels: enhancement, module [core]

#1027 Add --repo-retention-full-type option.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/command/expire/expire.c
  src/common/time.h
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/config.h
  src/config/define.auto.c
  src/config/define.auto.h
  src/config/load.c
  src/config/parse.auto.c
  test/define.yaml
  test/expect/mock-all-001.log
  test/expect/mock-all-002.log
  test/expect/mock-expire-001.log
  test/expect/mock-expire-002.log
  test/src/module/command/expireTest.c
  test/src/module/command/helpTest.c
  test/src/module/config/loadTest.c
Labels: enhancement, module [core]

#1028 Update what kind of assertions are fired for bzip2
  doc/xml/release.xml
  src/common/compress/bz2/common.c
  src/common/compress/gz/common.c
  test/src/module/common/compressTest.c
Labels: enhancement, module [doc]

#1034 Fix documentation reference to archive-get
  doc/xml/reference.xml
  src/config/define.auto.c
Labels: bug, module [doc]

#1041 Add local MD5 implementation so S3 works when FIPS is enabled.
  doc/xml/release.xml
  src/common/crypto/hash.c
  src/common/crypto/md5.vendor.c
  test/define.yaml
  test/src/module/common/cryptoTest.c
Labels: enhancement, module [core]

#1048 Fix possibly missing pg1-* options for the remote command.
  doc/xml/release.xml
  src/protocol/helper.c
  test/src/module/protocol/protocolTest.c
Labels: bug, module [core]

#1050 Ignore pg-host* and repo-host* options for the remote command.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/release.xml
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/define.auto.c
  src/config/define.auto.h
  src/config/parse.auto.c
  src/protocol/helper.c
  test/src/module/config/parseTest.c
  test/src/module/protocol/protocolTest.c
Labels: bug, module [core]

#1054 Improve handling of invalid HTTP response status.
  doc/xml/release.xml
  src/common/io/http/client.c
  test/src/module/common/ioHttpTest.c
Labels: enhancement, module [core]
