Repository pgbackrest/pgbackrest, pull requests merged in 2020-09, with the labels that each got.

#1164 Allow ProtocolParallel to complete with no jobs.
  doc/xml/release.xml
  src/protocol/parallel.c
  src/protocol/parallel.h
  test/src/module/protocol/protocolTest.c
Labels: enhancement, module [core]

#1171 Improve working directory error message.
  doc/xml/release.xml
  src/command/archive/common.c
  test/src/module/command/archiveCommonTest.c
Labels: enhancement, module [core]

#1172 Ignore backup_manifest for PG13.
  doc/xml/release.xml
  src/info/manifest.c
  src/postgres/interface.h
  test/src/module/info/manifestTest.c
Labels: enhancement, module [core]

#1175 Error with hints when backup user cannot read pg_settings.
  doc/xml/release.xml
  src/db/db.c
  test/src/module/db/dbTest.c
Labels: bug, module [core]

#1174 Improve PostgreSQL version identification.
  doc/xml/release.xml
  src/command/backup/backup.c
  src/command/restore/restore.c
  src/command/stanza/create.c
  src/command/stanza/upgrade.c
  src/info/infoArchive.c
  src/info/infoBackup.c
  src/info/infoBackup.h
  src/info/infoPg.c
  src/info/infoPg.h
  src/info/manifest.c
  src/info/manifest.h
  src/postgres/interface.c
  src/postgres/interface.h
  src/postgres/interface/version.h
  src/postgres/interface/version.intern.h
  src/postgres/interface/version.vendor.h
  test/src/module/command/backupTest.c
  test/src/module/command/checkTest.c
  test/src/module/command/restoreTest.c
  test/src/module/command/stanzaTest.c
  test/src/module/info/infoBackupTest.c
  test/src/module/info/infoPgTest.c
  test/src/module/info/manifestTest.c
  test/src/module/performance/typeTest.c
  test/src/module/postgres/interfaceTest.c
Labels: enhancement, module [core]

#1181 Update yum repository path for CentOS/RHEL user guide.
  doc/xml/release.xml
  doc/xml/user-guide.xml
Labels: enhancement, module [doc]

#1167 Add internal verify command.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  src/Makefile.in
  src/command/local/local.c
  src/command/verify/file.c
  src/command/verify/file.h
  src/command/verify/protocol.c
  src/command/verify/protocol.h
  src/command/verify/verify.c
  src/command/verify/verify.h
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/define.auto.c
  src/config/define.auto.h
  src/main.c
  test/define.yaml
  test/src/module/command/verifyTest.c
Labels: enhancement, module [core]

#1184 Add hint and documentation for protocol version mismatches.
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/protocol/client.c
  test/src/module/protocol/protocolTest.c
Labels: enhancement, module [core]

#1185 Move info command text to the reference and link to user guide.
  doc/lib/pgBackRestDoc/Common/DocRender.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
Labels: enhancement, module [doc]
