Repository pgbackrest/pgbackrest, pull requests merged in 2020-10, with the labels that each got.

#1190 Add repo-azure-endpoint option.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/define.auto.c
  src/config/define.auto.h
  src/config/parse.auto.c
  src/storage/azure/storage.c
  src/storage/azure/storage.h
  src/storage/helper.c
  test/src/module/command/helpTest.c
  test/src/module/storage/azureTest.c
Labels: enhancement

#1179 Add option groups.
  build/lib/pgBackRestBuild/Config/Build.pm
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/release.xml
  src/command/check/check.c
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/config.c
  src/config/config.h
  src/config/load.c
  src/db/helper.c
  test/src/module/config/configTest.c
  test/src/module/config/loadTest.c
Labels: enhancement, module [core]

#1192 Optimize small reads in IoRead.
  doc/xml/release.xml
  src/common/io/read.c
Labels: enhancement, module [core]

#1196 Expire history files.
  doc/xml/release.xml
  src/command/archive/common.c
  src/command/archive/common.h
  src/command/expire/expire.c
  test/src/module/command/expireTest.c
Labels: enhancement

#1210 Allow [, #, and space as the first character in database names.
  doc/xml/release.xml
  src/common/ini.c
  src/common/ini.h
  src/info/info.c
  test/src/module/command/backupTest.c
  test/src/module/common/iniTest.c
  test/src/module/info/manifestTest.c
Labels: bug, module [core]

#1217 Remove unused FUNCTION_LOG_VERIFY_WAL_RANGE* defines.
  src/command/verify/verify.c
Labels: enhancement, module [core]

#1207 Use zero-based indexes when referring to option indexes.
  doc/xml/release.xml
  src/command/archive/get/get.c
  src/command/archive/push/push.c
  src/command/backup/backup.c
  src/command/check/check.c
  src/command/check/common.c
  src/command/check/common.h
  src/command/restore/restore.c
  src/command/stanza/common.c
  src/command/verify/verify.c
  src/db/helper.c
  src/db/helper.h
  src/protocol/helper.c
  src/protocol/helper.h
  src/storage/helper.c
  src/storage/helper.h
  test/src/module/command/backupTest.c
  test/src/module/command/checkTest.c
  test/src/module/db/dbTest.c
  test/src/module/protocol/protocolTest.c
  test/src/module/storage/posixTest.c
Labels: enhancement, module [core]

#1191 Improve performance of large file lists in backup/restore commands.
  doc/xml/release.xml
  src/common/type/list.c
  test/define.yaml
  test/src/module/common/typeListTest.c
  test/src/module/performance/typeTest.c
Labels: enhancement

#1208 Improve info command output when a stanza is specified but missing.
  doc/xml/release.xml
  src/command/info/info.c
  test/src/module/command/infoTest.c
Labels: enhancement, module [core]
