Repository pgbackrest/pgbackrest, pull requests merged in 2021-03, with the labels that each got.

#1318 Add HttpUrl object.
  doc/xml/release.xml
  src/Makefile.in
  src/common/io/http/url.c
  src/common/io/http/url.h
  test/define.yaml
  test/src/module/common/ioHttpTest.c
Labels: enhancement, module [core]

#1321 Consolidate less commonly used repository storage options.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/lib/pgBackRestDoc/Common/DocConfig.pm
  doc/lib/pgBackRestDoc/Common/DocExecute.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/command/help/help.auto.c
  src/command/help/help.c
  src/config/config.auto.h
  src/config/load.c
  src/config/parse.auto.c
  src/storage/helper.c
  test/expect/mock-all-002.log
  test/expect/mock-archive-002.log
  test/expect/mock-archive-stop-002.log
  test/expect/mock-stanza-002.log
  test/lib/pgBackRestTest/Env/HostEnvTest.pm
  test/src/module/command/helpTest.c
  test/src/module/config/parseTest.c
  test/src/module/storage/azureTest.c
  test/src/module/storage/s3Test.c
Labels: enhancement, module [core]

#1320 GCS support for repository storage.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/index.xml
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/Makefile.in
  src/command/help/help.auto.c
  src/command/help/help.c
  src/command/repo/create.c
  src/common/io/http/request.c
  src/common/io/http/request.h
  src/common/io/http/response.h
  src/config/config.auto.h
  src/config/parse.auto.c
  src/storage/gcs/read.c
  src/storage/gcs/read.h
  src/storage/gcs/storage.c
  src/storage/gcs/storage.h
  src/storage/gcs/storage.intern.h
  src/storage/gcs/write.c
  src/storage/gcs/write.h
  src/storage/helper.c
  test/define.yaml
  test/expect/mock-archive-stop-001.log
  test/expect/mock-stanza-001.log
  test/lib/pgBackRestTest/Env/Host/HostBackupTest.pm
  test/lib/pgBackRestTest/Env/Host/HostBaseTest.pm
  test/lib/pgBackRestTest/Env/Host/HostGcsTest.pm
  test/lib/pgBackRestTest/Env/HostEnvTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockAllTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockArchiveStopTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockStanzaTest.pm
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
  test/src/module/command/helpTest.c
  test/src/module/storage/gcsTest.c
Labels: enhancement, module [core]

#1325 Clarify multi-repo and repo option for each command.
  doc/xml/reference.xml
  src/command/help/help.auto.c
Labels: enhancement, module [doc]

#1227 Multiple repository support.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/index.xml
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/command/help/help.auto.c
  src/config/load.c
  test/expect/real-all-001.log
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
  test/src/module/command/helpTest.c
  test/src/module/config/loadTest.c
Labels: enhancement, module [core]

#1327 Add compress-type clarification to archive-copy documentation.
  doc/xml/reference.xml
  doc/xml/release.xml
Labels: enhancement, module [doc]

#1328 Log archive copy during backup.
  doc/xml/release.xml
  src/command/backup/backup.c
  test/src/module/command/backupTest.c
Labels: enhancement, module [core]

#1329 Update selective restore documentation with caveats.
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
Labels: enhancement, module [doc]

#1307 Include recreated system databases during selective restore.
  doc/xml/release.xml
  src/command/restore/restore.c
  test/expect/mock-all-001.log
  test/src/module/command/restoreTest.c
Labels: enhancement, module [core]

#1336 Fix repo-ls / on S3 repositories.
  doc/xml/release.xml
  src/storage/s3/storage.c
  src/storage/storage.c
  test/src/module/storage/azureTest.c
  test/src/module/storage/gcsTest.c
  test/src/module/storage/posixTest.c
  test/src/module/storage/s3Test.c
Labels: bug

#1332 Improve protocol handlers.
  doc/xml/release.xml
  src/command/archive/get/get.c
  src/command/archive/get/protocol.c
  src/command/archive/get/protocol.h
  src/command/archive/push/protocol.c
  src/command/archive/push/protocol.h
  src/command/archive/push/push.c
  src/command/backup/protocol.c
  src/command/backup/protocol.h
  src/command/local/local.c
  src/command/remote/remote.c
  src/command/restore/protocol.c
  src/command/restore/protocol.h
  src/command/verify/protocol.c
  src/command/verify/protocol.h
  src/config/protocol.c
  src/config/protocol.h
  src/db/protocol.c
  src/db/protocol.h
  src/protocol/helper.c
  src/protocol/server.c
  src/protocol/server.h
  src/storage/remote/protocol.c
  src/storage/remote/protocol.h
  test/src/module/command/archiveGetTest.c
  test/src/module/command/archivePushTest.c
  test/src/module/command/backupTest.c
  test/src/module/command/restoreTest.c
  test/src/module/command/verifyTest.c
  test/src/module/config/protocolTest.c
  test/src/module/db/dbTest.c
  test/src/module/performance/storageTest.c
  test/src/module/protocol/protocolTest.c
  test/src/module/storage/remoteTest.c
Labels: enhancement, module [core]

#1341 Exclude content-length from S3 signed headers.
  doc/xml/release.xml
  src/storage/s3/storage.c
  test/src/module/storage/s3Test.c
Labels: enhancement, module [core]

#1342 Improve info command fault tolerance.
  doc/xml/reference.xml
  doc/xml/release.xml
  src/command/help/help.auto.c
  src/command/info/info.c
  test/src/module/command/infoTest.c
Labels: enhancement, module [core]

#1343 Improve archive-push command fault tolerance.
  doc/xml/release.xml
  src/command/archive/push/file.c
  src/command/archive/push/file.h
  src/command/archive/push/protocol.c
  src/command/archive/push/push.c
  test/expect/mock-archive-001.log
  test/expect/mock-archive-002.log
  test/expect/mock-archive-stop-001.log
  test/expect/mock-archive-stop-002.log
  test/expect/mock-stanza-001.log
  test/expect/mock-stanza-002.log
  test/lib/pgBackRestTest/Env/Host/HostDbCommonTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockArchiveStopTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockArchiveTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockStanzaTest.pm
  test/src/module/command/archivePushTest.c
Labels: enhancement, module [core]

#1298 Add archive-header-check option.
  doc/xml/reference.xml
  doc/xml/release.xml
  src/build/config/config.yaml
  src/command/archive/push/file.c
  src/command/archive/push/file.h
  src/command/archive/push/protocol.c
  src/command/archive/push/push.c
  src/command/help/help.auto.c
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/parse.auto.c
  test/src/module/command/archivePushTest.c
Labels: enhancement, module [core]

#1346 Add compress-level defaults per compress-type value.
  doc/xml/reference.xml
  doc/xml/release.xml
  src/command/help/help.auto.c
Labels: enhancement, module [core]

#1347 Add note about required NFS settings being the same as PostgreSQL.
  doc/xml/reference.xml
  doc/xml/release.xml
  src/command/help/help.auto.c
Labels: enhancement, module [doc]
