Repository pgbackrest/pgbackrest, pull requests merged in 2021-05, with the labels that each got.

#1385 Convert BackupType enum to StringId.
  doc/xml/release.xml
  src/command/backup/backup.c
  src/command/backup/common.c
  src/command/backup/common.h
  src/command/expire/expire.c
  src/command/info/info.c
  src/common/type/stringId.h
  src/config/config.h
  src/config/load.c
  src/info/infoBackup.c
  src/info/infoBackup.h
  src/info/manifest.c
  src/info/manifest.h
  test/define.yaml
  test/src/module/command/backupCommonTest.c
  test/src/module/command/backupTest.c
  test/src/module/info/infoBackupTest.c
Labels: enhancement, module [core]

#1371 Fix issues with leftover spool files from a prior restore.
  doc/xml/release.xml
  src/command/archive/common.c
  src/command/archive/common.h
  src/command/archive/get/get.c
  src/command/archive/push/push.c
  test/src/module/command/archiveCommonTest.c
  test/src/module/command/archiveGetTest.c
Labels: bug, module [core]

#1395 Add automatic GCS authentication for GCE instances.
  doc/xml/reference.xml
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/build/config/config.yaml
  src/command/help/help.auto.c
  src/config/config.auto.h
  src/config/parse.auto.c
  src/storage/gcs/storage.c
  src/storage/gcs/storage.h
  src/storage/helper.c
  test/src/module/storage/gcsTest.c
Labels: enhancement, module [core]

#1386 Remove stanza archive spool path on restore.
  doc/xml/release.xml
  src/build/config/config.yaml
  src/command/help/help.auto.c
  src/command/restore/restore.c
  src/config/parse.auto.c
  src/storage/helper.c
  src/storage/helper.h
  test/expect/mock-all-001.log
  test/src/module/command/restoreTest.c
  test/src/module/storage/posixTest.c
Labels: enhancement, module [core]

#1410 Rename default command role to main.
  build/lib/pgBackRestBuild/Config/BuildParse.pm
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/lib/pgBackRestDoc/Common/DocConfig.pm
  doc/xml/release.xml
  src/build/config/config.yaml
  src/command/help/help.c
  src/command/restore/restore.c
  src/config/config.c
  src/config/config.h
  src/config/load.c
  src/config/parse.auto.c
  src/config/parse.c
  src/main.c
  test/src/common/harnessConfig.c
  test/src/module/command/archivePushTest.c
  test/src/module/command/commandTest.c
  test/src/module/common/exitTest.c
  test/src/module/config/execTest.c
  test/src/module/config/parseTest.c
Labels: enhancement, module [core]

#1396 Replace getopt_long() with custom implementation.
  doc/xml/release.xml
  src/command/help/help.c
  src/config/parse.c
  src/config/parse.h
  src/config/protocol.c
  test/src/module/config/parseTest.c
Labels: enhancement, module [core]

#1400 Update contributing documentation.
  CONTRIBUTING.md
  README.md
  doc/xml/contributing.xml
  doc/xml/index.xml
  doc/xml/release.xml
Labels: enhancement, module [doc]

#1405 Consolidate RHEL/CentOS user guide into a single document.
  CONTRIBUTING.md
  doc/README.md
  doc/RELEASE.md
  doc/release.pl
  doc/xml/contributing.xml
  doc/xml/documentation.xml
  doc/xml/release.xml
  doc/xml/user-guide-index.xml
  doc/xml/user-guide.xml
Labels: enhancement, module [doc]

#1356 Fix issue when checking links for large numbers of tablespaces.
  doc/xml/release.xml
  src/info/manifest.c
  src/info/manifest.h
  test/src/module/info/manifestTest.c
Labels: bug, module [core]

#1413 Add PostgreSQL 14 support.
  doc/xml/release.xml
  src/Makefile.in
  src/postgres/interface.c
  src/postgres/interface/v140.c
  src/postgres/interface/version.h
  src/postgres/interface/version.intern.h
  src/postgres/interface/version.vendor.h
  src/postgres/version.h
  test/container.yaml
  test/define.yaml
  test/lib/pgBackRestTest/Common/ContainerTest.pm
  test/lib/pgBackRestTest/Common/DbVersion.pm
  test/lib/pgBackRestTest/Common/VmTest.pm
  test/lib/pgBackRestTest/Env/Host/HostDbTest.pm
  test/lib/pgBackRestTest/Env/HostEnvTest.pm
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
  test/src/common/harnessPostgres.c
  test/src/common/harnessPostgres/harness140.c
Labels: enhancement, module [core]

#1389 Add repo-retention-history option to expire backup history.
  doc/xml/reference.xml
  doc/xml/release.xml
  src/build/config/config.yaml
  src/command/backup/backup.c
  src/command/backup/common.c
  src/command/backup/common.h
  src/command/expire/expire.c
  src/command/help/help.auto.c
  src/config/config.auto.h
  src/config/parse.auto.c
  test/src/module/command/expireTest.c
Labels: enhancement, module [core]
