Repository pgbackrest/pgbackrest, pull requests merged in 2021-01, with the labels that each got.

#1267 Remove duplicate tests from command/infoTest.c.
  test/src/module/command/infoTest.c
Labels: enhancement, module [test]

#1273 Add job-retry and job-retry-interval options.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/release.xml
  src/command/help/help.auto.c
  src/command/local/local.c
  src/command/restore/restore.c
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/config.c
  src/config/config.intern.h
  src/config/parse.auto.c
  test/expect/mock-all-001.log
  test/expect/mock-all-002.log
  test/expect/mock-archive-001.log
  test/expect/mock-archive-002.log
  test/expect/mock-stanza-001.log
  test/expect/mock-stanza-002.log
  test/expect/real-all-001.log
  test/lib/pgBackRestTest/Env/Host/HostBackupTest.pm
  test/src/common/harnessConfig.c
  test/src/module/config/parseTest.c
Labels: enhancement, module [core]

#1272 Fix resume after partial delete of backup by prior resume.
  doc/xml/release.xml
  src/command/backup/backup.c
  test/src/module/command/backupTest.c
Labels: bug, module [core]

#1274 Improve archive-get performance
  doc/xml/release.xml
  src/command/archive/get/file.c
  src/command/archive/get/file.h
  src/command/archive/get/get.c
  src/command/archive/get/protocol.c
  test/define.yaml
  test/expect/mock-archive-001.log
  test/expect/mock-archive-002.log
  test/expect/mock-stanza-001.log
  test/expect/mock-stanza-002.log
  test/src/module/command/archiveGetTest.c
Labels: enhancement, module [core]

#1275 Update info command to allow for multiple repositories.
  doc/xml/reference.xml
  src/command/help/help.auto.c
  src/command/info/info.c
  src/config/load.c
  test/src/module/command/infoTest.c
  test/src/module/config/loadTest.c
Labels: enhancement, module [core]

#1281 Partial multi-repository implementation.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/lib/pgBackRestDoc/Common/DocConfig.pm
  doc/xml/dtd/doc.dtd
  doc/xml/release.xml
  src/command/archive/push/file.c
  src/command/archive/push/file.h
  src/command/archive/push/protocol.c
  src/command/archive/push/push.c
  src/command/check/check.c
  src/command/help/help.auto.c
  src/command/help/help.c
  src/command/info/info.c
  src/command/stanza/create.c
  src/command/stanza/delete.c
  src/command/stanza/upgrade.c
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/config.c
  src/config/config.intern.h
  src/config/load.c
  src/config/parse.auto.c
  src/config/parse.c
  src/protocol/helper.c
  src/protocol/helper.h
  test/define.yaml
  test/expect/mock-all-001.log
  test/expect/mock-all-002.log
  test/expect/mock-archive-001.log
  test/expect/mock-archive-002.log
  test/expect/mock-archive-stop-001.log
  test/expect/mock-archive-stop-002.log
  test/expect/mock-stanza-001.log
  test/expect/mock-stanza-002.log
  test/expect/real-all-001.log
  test/lib/pgBackRestTest/Common/StorageRepo.pm
  test/lib/pgBackRestTest/Env/Host/HostBackupTest.pm
  test/lib/pgBackRestTest/Env/HostEnvTest.pm
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
  test/src/module/command/archiveGetTest.c
  test/src/module/command/archivePushTest.c
  test/src/module/command/backupTest.c
  test/src/module/command/checkTest.c
  test/src/module/command/expireTest.c
  test/src/module/command/infoTest.c
  test/src/module/command/remoteTest.c
  test/src/module/command/restoreTest.c
  test/src/module/command/stanzaTest.c
  test/src/module/command/verifyTest.c
  test/src/module/config/loadTest.c
  test/src/module/config/parseTest.c
  test/src/module/protocol/protocolTest.c
  test/src/module/storage/remoteTest.c
Labels: enhancement, module [core]

#1282 Update the info command text output and --set handling.
  doc/xml/reference.xml
  src/command/help/help.auto.c
  src/command/info/info.c
  test/src/module/command/infoTest.c
Labels: enhancement, module [core]

#1257 Add backup verification to internal verify command.
  doc/xml/release.xml
  src/command/verify/verify.c
  test/define.yaml
  test/src/module/command/verifyTest.c
Labels: enhancement, module [core]

#1285 Update expire command log messages with repo prefix.
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/command/expire/expire.c
  test/expect/mock-all-001.log
  test/expect/mock-expire-001.log
  test/expect/mock-expire-002.log
  test/expect/mock-stanza-001.log
  test/expect/mock-stanza-002.log
  test/src/module/command/expireTest.c
Labels: enhancement
