Repository pgbackrest/pgbackrest, pull requests merged in 2021-02, with the labels that each got.

#1287 Add archive-mode-check option.
  build/lib/pgBackRestBuild/Config/Data.pm
  doc/xml/reference.xml
  doc/xml/release.xml
  src/command/check/common.c
  src/command/help/help.auto.c
  src/config/config.auto.c
  src/config/config.auto.h
  src/config/parse.auto.c
  test/src/module/command/checkTest.c
Labels: enhancement, module [core]

#1289 Enhance expire command multi-repo support.
  doc/xml/reference.xml
  src/command/backup/backup.c
  src/command/backup/common.c
  src/command/backup/common.h
  src/command/expire/expire.c
  src/command/help/help.auto.c
  src/config/load.c
  test/src/module/command/expireTest.c
Labels: enhancement, module [core]

#1295 Fix stack overflow in cipher passphrase generation.
  doc/xml/release.xml
  src/command/stanza/common.c
Labels: bug, module [core]

#1301 Fix option warnings breaking async archive-get/archive-push.
  doc/xml/release.xml
  src/config/parse.c
  test/src/module/config/parseTest.c
Labels: bug, module [core]

#1308 Enhance expire to continue processing when a repo fails.
  build/error.yaml
  doc/xml/user-guide.xml
  src/command/expire/expire.c
  src/common/error.auto.c
  src/common/error.auto.h
  test/expect/mock-all-001.log
  test/expect/mock-expire-001.log
  test/expect/mock-expire-002.log
  test/expect/mock-stanza-001.log
  test/expect/mock-stanza-002.log
  test/src/module/command/expireTest.c
Labels: enhancement, module [core]

#1292 Enhance the archive-get command for multi-repo support
  build/error.yaml
  doc/xml/reference.xml
  src/command/archive/get/file.c
  src/command/archive/get/file.h
  src/command/archive/get/get.c
  src/command/archive/get/protocol.c
  src/command/help/help.auto.c
  src/common/error.auto.c
  src/common/error.auto.h
  src/config/load.c
  test/expect/mock-archive-001.log
  test/expect/mock-archive-002.log
  test/expect/mock-stanza-001.log
  test/expect/mock-stanza-002.log
  test/lib/pgBackRestTest/Env/Host/HostBackupTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockArchiveTest.pm
  test/src/common/harnessStorage.c
  test/src/common/harnessStorage.h
  test/src/module/command/archiveGetTest.c
Labels: enhancement, module [core]

#1309 Update the info command to use repoIdxMin/Max same as expire command.
  src/command/info/info.c
Labels: enhancement, module [core]

#1255 Allow custom config-path default with ./configure --with-configdir.
  doc/xml/release.xml
  src/build/configure.ac
  src/configure
Labels: enhancement, module [build]

#1315 Repo option is optional when performing a backup.
  doc/xml/reference.xml
  src/command/backup/backup.c
  src/command/help/help.auto.c
  src/config/load.c
  test/expect/mock-all-001.log
  test/expect/mock-all-002.log
  test/expect/mock-stanza-001.log
  test/expect/mock-stanza-002.log
  test/expect/real-all-001.log
  test/lib/pgBackRestTest/Env/Host/HostBackupTest.pm
  test/src/module/command/backupTest.c
  test/src/module/config/loadTest.c
Labels: enhancement, module [core]

#1316 Add write fault-tolerance to archive-push command.
  .cirrus.yml
  src/command/archive/push/file.c
  src/command/archive/push/file.h
  src/command/archive/push/protocol.c
  src/command/archive/push/push.c
  test/src/module/command/archivePushTest.c
Labels: enhancement, module [core]
