Repository pgbackrest/pgbackrest, pull requests merged in 2022-11, with the labels that each got.

#1920 Update test.pl --psql-bin option to match command-line help.
  doc/xml/release.xml
  test/lib/pgBackRestTest/Common/JobTest.pm
  test/lib/pgBackRestTest/Common/ListTest.pm
  test/lib/pgBackRestTest/Common/VmTest.pm
  test/test.pl
Labels: enhancement, module [test]

#1929 Add hint when an option is specified without an index.
  doc/xml/release.xml
  src/config/parse.c
  test/src/module/config/parseTest.c
Labels: module [core], enhancement

#1935 Fix missing reference in diff/incr backup.
  doc/xml/release.xml
  src/info/infoBackup.c
  src/info/manifest.c
  test/src/module/info/manifestTest.c
Labels: bug, module [core]
