Repository pgbackrest/pgbackrest, pull requests merged in 2022-02, with the labels that each got.

#1652 Remove logic that tried to determine additional file system compression.
  doc/xml/release.xml
  src/build/help/help.xml
  src/command/backup/file.c
  src/storage/posix/storage.c
  src/storage/storage.h
  test/src/module/command/backupTest.c
  test/src/module/storage/azureTest.c
  test/src/module/storage/gcsTest.c
  test/src/module/storage/posixTest.c
  test/src/module/storage/remoteTest.c
  test/src/module/storage/s3Test.c
Labels: module [core], enhancement

#1651 Add backup type filter to info command.
  doc/xml/release.xml
  src/build/config/config.yaml
  src/build/help/help.xml
  src/command/info/info.c
  src/config/parse.auto.c
  test/src/module/command/infoTest.c
Labels: module [core], enhancement

#1653 Retry errors in S3 batch file delete.
  doc/xml/release.xml
  src/storage/s3/storage.c
  test/src/module/storage/s3Test.c
Labels: bug, module [core]

#1658 Do not retry fatal errors.
  doc/xml/release.xml
  src/build/error/error.yaml
  src/build/error/parse.c
  src/build/error/parse.h
  src/build/error/render.c
  src/command/archive/push/push.c
  src/common/error.auto.c
  src/common/error.c
  src/common/error.h
  src/main.c
  src/protocol/server.c
  test/src/common/harnessTest.h
  test/src/module/build/errorTest.c
  test/src/module/common/errorTest.c
  test/src/module/common/exitTest.c
  test/src/module/protocol/protocolTest.c
  test/src/test.c
Labels: module [core], enhancement

#1655 Bundle files in the repository during backup.
  doc/xml/release.xml
  src/build/config/config.yaml
  src/build/help/help.xml
  src/command/backup/backup.c
  src/command/backup/file.c
  src/command/backup/file.h
  src/command/backup/protocol.c
  src/command/restore/file.c
  src/command/restore/file.h
  src/command/restore/protocol.c
  src/command/restore/restore.c
  src/command/verify/file.c
  src/command/verify/file.h
  src/command/verify/protocol.c
  src/command/verify/verify.c
  src/config/config.auto.h
  src/config/parse.auto.c
  src/info/manifest.c
  src/info/manifest.h
  test/expect/real-all-001.log
  test/lib/pgBackRestTest/Env/ExpireEnvTest.pm
  test/lib/pgBackRestTest/Env/Host/HostBackupTest.pm
  test/lib/pgBackRestTest/Env/HostEnvTest.pm
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
  test/src/module/command/backupTest.c
  test/src/module/command/restoreTest.c
  test/src/module/command/verifyTest.c
  test/src/module/info/manifestTest.c
  test/src/module/performance/typeTest.c
Labels: module [core], enhancement

#1662 Limit files that can be bundled.
  doc/xml/release.xml
  src/build/config/config.yaml
  src/build/help/help.xml
  src/command/backup/backup.c
  src/config/config.auto.h
  src/config/parse.auto.c
  test/src/module/command/backupTest.c
Labels: module [core], enhancement

#1642 Add archive-missing-retry option.
  doc/xml/release.xml
  src/build/config/config.yaml
  src/build/help/help.xml
  src/command/archive/get/get.c
  src/config/config.auto.h
  src/config/parse.auto.c
  test/src/module/command/archiveGetTest.c
Labels: module [core], enhancement

#1672 Disconnect help.auto.c from build-help in Makefile
  doc/xml/release.xml
  src/Makefile.in
Labels: module [build], enhancement

#1669 Improve validation of zero pages.
  doc/xml/release.xml
  src/command/backup/pageChecksum.c
  test/src/module/command/backupTest.c
Labels: module [core], enhancement

#1673 Automatically strip trailing slashes for repo-ls paths.
  doc/xml/release.xml
  src/command/repo/ls.c
  test/src/module/command/repoTest.c
Labels: module [core], enhancement

#1675 Allow case-insensitive matching of HTTP connection header values.
  doc/xml/release.xml
  src/common/io/http/response.c
  test/src/module/common/ioHttpTest.c
Labels: bug, module [core]

#1664 Add FAQ explaining WAL archive suffix.
  doc/xml/faq.xml
  doc/xml/release.xml
Labels: enhancement, module [doc]
