Repository pgbackrest/pgbackrest, pull requests merged in 2022-05, with the labels that each got.

#1730 Error on all lock failures except another process holding the lock.
  doc/xml/release.xml
  src/common/lock.c
  test/src/module/common/lockTest.c
Labels: bug, module [core]

#1732 Fix error thrown from FINALLY() causing an infinite loop.
  doc/xml/release.xml
  src/common/error.c
  src/common/error.h
  test/src/module/common/errorTest.c
Labels: bug, module [core]

#1735 Remove dependency on pg_database.datlastsysoid.
  doc/xml/release.xml
  src/command/info/info.c
  src/command/restore/restore.c
  src/db/db.c
  src/info/manifest.h
  src/postgres/interface.c
  src/postgres/interface.h
  src/postgres/interface/static.vendor.h
  test/define.yaml
  test/src/common/harnessPq.h
  test/src/module/command/infoTest.c
  test/src/module/command/restoreTest.c
  test/src/module/info/manifestTest.c
  test/src/module/postgres/interfaceTest.c
Labels: module [core], enhancement

#1621 Show backup percent complete in info output.
  doc/xml/release.xml
  src/command/backup/backup.c
  src/command/info/info.c
  src/common/lock.c
  src/common/lock.h
  src/main.c
  test/expect/mock-all-001.log
  test/expect/mock-stanza-001.log
  test/expect/mock-stanza-002.log
  test/src/module/command/backupTest.c
  test/src/module/command/controlTest.c
  test/src/module/command/infoTest.c
  test/src/module/common/lockTest.c
Labels: module [core], enhancement

#1734 Prevent memContextFree() from freeing memory needed by callbacks.
  doc/xml/release.xml
  src/common/io/tls/client.c
  src/common/io/tls/session.c
  src/common/memContext.c
  src/common/memContext.h
  src/common/type/object.h
  test/src/module/common/memContextTest.c
  test/src/module/common/typeObjectTest.c
Labels: module [core], enhancement

#1738 Strip extensions from history manifest before showing in error message.
  doc/xml/release.xml
  src/command/backup/backup.c
  src/info/manifest.h
  test/src/module/command/backupTest.c
Labels: module [core], enhancement

#1739 Add ClockError for unexpected clock skew and timezone changes.
  doc/xml/release.xml
  src/build/error/error.yaml
  src/command/backup/backup.c
  src/common/error.auto.c
  src/common/error.auto.h
  test/src/module/command/backupTest.c
Labels: module [core], enhancement

#1740 Backup file bundling documentation.
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/build/config/config.yaml
Labels: module [core], enhancement

#1607 Add verify output and verbose options.
  doc/xml/release.xml
  src/build/config/config.yaml
  src/build/help/help.xml
  src/command/verify/verify.c
  src/config/config.auto.h
  src/config/parse.auto.c
  test/define.yaml
  test/src/module/command/helpTest.c
  test/src/module/command/verifyTest.c
Labels: module [core], enhancement

#1744 Use variable instead of function to track FINALLY() state.
  doc/xml/release.xml
  src/common/error.c
  src/common/error.h
  test/src/module/common/errorTest.c
Labels: module [core], enhancement

#1742 Simplify messaging around supported versions in the documentation.
  doc/xml/release.xml
  doc/xml/user-guide-index.xml
  doc/xml/user-guide.xml
Labels: enhancement, module [doc]

#1733 Document required base branch for pull requests.
  CONTRIBUTING.md
  doc/xml/contributing.xml
  doc/xml/release.xml
Labels: enhancement, module [doc]

#1751 Fix issues in improved path validation for repo-* commands.
  doc/xml/release.xml
  src/command/repo/common.c
  test/src/module/command/repoTest.c
Labels: module [core], enhancement

#1758 Truncate files during delta restore when they are larger than expected.
  doc/xml/release.xml
  src/command/restore/file.c
  test/src/module/command/restoreTest.c
Labels: module [core], enhancement

#1760 Disable incremental manifest save when resume=n.
  doc/xml/release.xml
  src/command/backup/backup.c
  test/src/module/command/backupTest.c
Labels: module [core], enhancement

#1764 Allow any path to be passed to the --test-path option.
  doc/xml/release.xml
  test/lib/pgBackRestTest/Common/JobTest.pm
Labels: enhancement, module [test]
