Repository pgbackrest/pgbackrest, pull requests merged in 2023-09, with the labels that each got.

#2162 Improve GCS multi-part performance.
  doc/xml/release.xml
  src/storage/gcs/write.c
  test/src/module/storage/gcsTest.c
Labels: module [core], enhancement

#2165 Fix configuration reference example for the tls-server-address option.
  doc/xml/release/2023/2.48.xml
  doc/xml/release/contributor.xml
  src/build/help/help.xml
Labels: bug, module [doc]

#2131 Retry reads of pg_control until checksum is valid.
  doc/xml/release/2023/2.48.xml
  src/Makefile.in
  src/command/backup/backup.c
  src/command/backup/file.c
  src/command/backup/file.h
  src/command/backup/protocol.c
  src/meson.build
  src/postgres/interface.c
  src/postgres/interface.h
  src/postgres/interface/crc32.c
  src/postgres/interface/crc32.h
  src/postgres/interface/version.intern.h
  test/define.yaml
  test/lib/pgBackRestTest/Env/HostEnvTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockAllTest.pm
  test/src/common/harnessBackup.c
  test/src/common/harnessPostgres.c
  test/src/common/harnessPostgres.h
  test/src/common/harnessPostgres/harnessVersion.intern.h
  test/src/module/command/backupTest.c
  test/src/module/postgres/interfaceTest.c
Labels: module [core], enhancement

#2174 Refactor address list lookup to include all returned addresses.
  src/Makefile.in
  src/common/io/socket/address.c
  src/common/io/socket/address.h
  src/common/io/socket/client.c
  src/common/io/socket/common.c
  src/common/io/socket/common.h
  src/common/io/socket/server.c
  src/meson.build
  test/define.yaml
  test/src/module/common/ioHttpTest.c
  test/src/module/common/ioTlsTest.c
Labels: module [core], enhancement

#2169 Optimize WAL segment check after successful backup.
  doc/xml/release/2023/2.48.xml
  src/Makefile.in
  src/command/archive/common.c
  src/command/archive/common.h
  src/command/archive/find.c
  src/command/archive/find.h
  src/command/archive/push/file.c
  src/command/backup/backup.c
  src/command/check/check.c
  src/meson.build
  test/define.yaml
  test/src/module/command/archiveCommonTest.c
Labels: module [core], enhancement

#2175 Support for dual stack connections.
  doc/xml/release/2023/2.48.xml
  src/common/io/socket/client.c
  test/src/module/common/ioHttpTest.c
  test/src/module/common/ioTlsTest.c
Labels: module [core], enhancement

#2159 Add --repo-storage-tag option to create object tags.
  doc/xml/release/2023/2.48.xml
  doc/xml/release/contributor.xml
  doc/xml/user-guide.xml
  src/build/config/config.yaml
  src/build/help/help.xml
  src/common/io/http/query.c
  src/common/io/http/query.h
  src/config/config.auto.h
  src/config/parse.auto.c.inc
  src/storage/azure/helper.c
  src/storage/azure/storage.c
  src/storage/azure/storage.h
  src/storage/azure/storage.intern.h
  src/storage/azure/write.c
  src/storage/gcs/helper.c
  src/storage/gcs/storage.c
  src/storage/gcs/storage.h
  src/storage/gcs/storage.intern.h
  src/storage/gcs/write.c
  src/storage/gcs/write.h
  src/storage/s3/helper.c
  src/storage/s3/storage.c
  src/storage/s3/storage.h
  src/storage/s3/storage.intern.h
  src/storage/s3/write.c
  test/define.yaml
  test/src/module/command/helpTest.c
  test/src/module/common/ioHttpTest.c
  test/src/module/storage/azureTest.c
  test/src/module/storage/gcsTest.c
  test/src/module/storage/s3Test.c
Labels: module [core], enhancement

#2176 Add report option to check command.
  doc/xml/release/2023/2.48.xml
  src/Makefile.in
  src/build/config/config.yaml
  src/build/help/help.xml
  src/command/check/check.c
  src/command/check/report.c
  src/command/check/report.h
  src/config/config.auto.h
  src/config/parse.auto.c.inc
  src/config/parse.c
  src/config/parse.h
  src/meson.build
  test/define.yaml
  test/src/module/command/checkTest.c
  test/src/module/config/parseTest.c
Labels: module [core], enhancement

#2125 Add known hosts checking for SFTP storage driver.
  doc/xml/release/2023/2.48.xml
  doc/xml/user-guide.xml
  src/build/config/config.yaml
  src/build/help/help.xml
  src/common/user.c
  src/config/config.auto.h
  src/config/load.c
  src/config/parse.auto.c.inc
  src/storage/sftp/helper.c
  src/storage/sftp/storage.c
  src/storage/sftp/storage.h
  test/lib/pgBackRestTest/Env/Host/HostBackupTest.pm
  test/src/common/harnessLibSsh2.c
  test/src/common/harnessLibSsh2.h
  test/src/module/command/helpTest.c
  test/src/module/config/loadTest.c
  test/src/module/storage/sftpTest.c
Labels: module [core], enhancement

#2177 Allow storage/sftp unit test to run without libssh2 installed.
  doc/xml/release/2023/2.48.xml
  doc/xml/release/contributor.xml
  test/src/module/common/userTest.c
  test/src/module/config/loadTest.c
  test/src/module/storage/sftpTest.c
Labels: enhancement, module [test]

#2195 Fix common/lock test failing with -Werror=unused-result.
  test/src/module/common/lockTest.c
Labels: enhancement, module [test]
