Repository pgbackrest/pgbackrest, pull requests merged in 2023-11, with the labels that each got.

#2221 Fix regression in retries.
  doc/xml/release/2023/2.49.xml
  doc/xml/release/contributor.xml
  src/common/io/socket/client.c
  src/common/wait.c
  src/common/wait.h
  test/src/module/common/ioHttpTest.c
  test/src/module/common/ioTlsTest.c
  test/src/module/common/waitTest.c
  test/src/module/db/dbTest.c
  test/src/module/postgres/clientTest.c
  test/src/module/storage/sftpTest.c
Labels: bug, module [core]

#2220 Remove support for PostgreSQL 9.3.
  README.md
  doc/xml/index.xml
  doc/xml/release/2023/2.49.xml
  src/build/help/help.xml
  src/build/postgres/postgres.yaml
  src/info/manifest.c
  src/postgres/interface/version.intern.h
  src/postgres/interface/version.vendor.h
  src/postgres/version.auto.h
  test/code-count/file-type.yaml
  test/container.yaml
  test/lib/pgBackRestTest/Common/DbVersion.pm
  test/lib/pgBackRestTest/Common/VmTest.pm
  test/lib/pgBackRestTest/Env/ExpireEnvTest.pm
  test/lib/pgBackRestTest/Env/Host/HostDbTest.pm
  test/lib/pgBackRestTest/Env/HostEnvTest.pm
  test/lib/pgBackRestTest/Env/Manifest.pm
  test/lib/pgBackRestTest/Module/Mock/MockExpireTest.pm
  test/lib/pgBackRestTest/Module/Mock/MockStanzaTest.pm
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
  test/src/common/harnessPostgres.c
  test/src/common/harnessPostgres.h
  test/src/common/harnessPostgres/harness093.c
  test/src/common/harnessPostgres/harnessVersion.intern.h
  test/src/module/command/archiveCommonTest.c
  test/src/module/command/archiveGetTest.c
  test/src/module/command/backupTest.c
  test/src/module/command/checkTest.c
  test/src/module/command/infoTest.c
  test/src/module/command/stanzaTest.c
  test/src/module/command/verifyTest.c
  test/src/module/db/dbTest.c
  test/src/module/info/manifestTest.c
  test/src/module/postgres/interfaceTest.c
  test/test.pl
Labels: module [core], enhancement

#2194 Allow config/load unit test to run without libssh2 installed.
  doc/xml/release.xml
  doc/xml/release/2023/2.49.xml
  test/src/module/config/loadTest.c
Labels: enhancement, module [test]

#2226 Fix recursive path remove in SFTP storage driver.
  doc/xml/release/2023/2.49.xml
  doc/xml/release/contributor.xml
  src/storage/sftp/storage.c
  test/src/module/storage/sftpTest.c
Labels: bug, module [core]
