Repository pgbackrest/pgbackrest, pull requests merged in 2023-07, with the labels that each got.

#2076 Error when pull request target branch is not integration.
  .github/workflows/target-branch.yml
  doc/xml/release.xml
Labels: enhancement, module [test]

#2109 Fix time-based archive expiration when no backups are expired.
  doc/xml/release.xml
  src/command/expire/expire.c
  test/src/module/command/expireTest.c
Labels: bug, module [core]

#2095 Add timezone offset to info command date/time output.
  .cirrus.yml
  doc/xml/release.xml
  src/command/info/info.c
  test/src/module/command/infoTest.c
Labels: module [core], enhancement

#2120 Fix block incremental file names in verify command.
  doc/xml/release.xml
  src/command/verify/verify.c
  test/src/module/command/verifyTest.c
Labels: bug, module [core]

#2123 Preserve block incremental info in manifest during delta backup.
  doc/xml/release.xml
  src/info/manifest.c
  test/src/module/command/backupTest.c
Labels: bug, module [core]

#2124 Fix spurious automatic delta backup on backup from standby.
  doc/xml/release.xml
  src/command/backup/backup.c
  src/info/manifest.c
  src/info/manifest.h
  test/src/common/harnessManifest.c
  test/src/common/harnessManifest.h
  test/src/module/command/backupTest.c
  test/src/module/info/manifestTest.c
Labels: bug, module [core]
