Repository pgbackrest/pgbackrest, pull requests merged in 2023-05, with the labels that each got.

#2053 Finalize block incremental feature.
  doc/xml/release.xml
  doc/xml/user-guide.xml
  src/build/config/config.yaml
  src/config/parse.auto.c.inc
Labels: module [core], enhancement

#1959 SFTP support for repository storage.
  doc/xml/release.xml
  doc/xml/user-guide.xml
  meson.build
  src/Makefile.in
  src/build.auto.h.in
  src/build/config/config.yaml
  src/build/configure.ac
  src/build/help/help.xml
  src/config/config.auto.h
  src/config/load.c
  src/config/parse.auto.c.inc
  src/configure
  src/main.c
  src/meson.build
  src/storage/sftp/helper.c
  src/storage/sftp/helper.h
  src/storage/sftp/read.c
  src/storage/sftp/read.h
  src/storage/sftp/storage.c
  src/storage/sftp/storage.h
  src/storage/sftp/storage.intern.h
  src/storage/sftp/write.c
  src/storage/sftp/write.h
  test/Dockerfile
  test/Vagrantfile
  test/certificate/ssh/id_rsa
  test/certificate/ssh/id_rsa.pub
  test/ci.pl
  test/code-count/file-type.yaml
  test/container.yaml
  test/define.yaml
  test/lib/pgBackRestTest/Common/ContainerTest.pm
  test/lib/pgBackRestTest/Common/VmTest.pm
  test/lib/pgBackRestTest/Env/Host/HostBackupTest.pm
  test/lib/pgBackRestTest/Env/Host/HostBaseTest.pm
  test/lib/pgBackRestTest/Env/Host/HostSftpTest.pm
  test/lib/pgBackRestTest/Env/HostEnvTest.pm
  test/lib/pgBackRestTest/Module/Real/RealAllTest.pm
  test/src/command/test/build.c
  test/src/common/harnessLibSsh2.c
  test/src/common/harnessLibSsh2.h
  test/src/common/harnessSocket.c
  test/src/common/harnessSocket.h
  test/src/module/command/helpTest.c
  test/src/module/config/loadTest.c
  test/src/module/storage/sftpTest.c
  test/src/module/test/testTest.c
  test/src/test.c
Labels: module [core], enhancement

#2069 Add warning about using recovery type=none.
  doc/xml/release.xml
  src/build/help/help.xml
Labels: enhancement, module [doc]

#2075 Centralize error handling for unsupported features.
  doc/xml/release.xml
  src/build/config/config.yaml
  src/build/config/parse.c
  src/build/config/parse.h
  src/build/config/render.c
  src/common/compress/helper.c
  src/common/compress/helper.h
  src/config/load.c
  src/config/parse.auto.c.inc
  src/config/parse.c
  test/src/module/build/configTest.c
  test/src/module/common/compressTest.c
  test/src/module/config/parseTest.c
Labels: module [core], enhancement

#2070 Skip recovery.signal for PostgreSQL >= 12 when recovery type=none.
  doc/xml/release.xml
  src/command/restore/restore.c
  test/src/module/command/restoreTest.c
Labels: bug, module [core]
