Repository pgbackrest/pgbackrest, pull requests merged in 2024-07, with the labels that each got.

#2389 Allow backups to run concurrently on different repositories.
  doc/src/build/config/config.yaml
  doc/src/build/help/help.xml
  doc/xml/release/2024/2.53.xml
  src/build/config/config.yaml
  src/command/control/stop.c
  src/command/info/info.c
  src/command/lock.c
  src/command/lock.h
  src/common/type/list.c
  src/common/type/list.h
  src/config/config.auto.h
  src/config/parse.auto.c.inc
  src/db/db.c
  src/protocol/helper.c
  test/src/build/config/config.yaml
  test/src/build/help/help.xml
  test/src/common/harnessBackup.c
  test/src/module/command/controlTest.c
  test/src/module/command/infoTest.c
  test/src/module/command/lockTest.c
  test/src/module/command/remoteTest.c
  test/src/module/common/typeListTest.c
  test/src/module/db/dbTest.c
  test/src/module/protocol/protocolTest.c
Labels: module [core], enhancement

#2377 Fix SFTP renaming failure when file already exists.
  doc/xml/release/2024/2.53.xml
  doc/xml/release/contributor.xml
  src/storage/sftp/storage.c
  src/storage/sftp/write.c
  test/src/module/storage/sftpTest.c
Labels: bug, module [core]

#2385 Add hint to check SFTP authorization log.
  doc/xml/release/2024/2.53.xml
  doc/xml/release/contributor.xml
  src/storage/sftp/storage.c
  test/src/module/storage/sftpTest.c
Labels: module [core], enhancement

#2047 Support IP-based SANs for TLS certificate validation.
  doc/xml/release/2024/2.53.xml
  src/common/io/tls/client.c
  src/common/io/tls/common.c
  src/common/io/tls/common.h
  test/certificate/pgbackrest-test-server.cnf
  test/certificate/pgbackrest-test-server.crt
  test/src/common/harnessServer.c
  test/src/common/harnessServer.h
  test/src/module/common/ioTlsTest.c
Labels: module [core], enhancement

#2398 Clarify archive-push multi-repo behavior.
  doc/xml/release/2024/2.53.xml
  doc/xml/user-guide.xml
Labels: enhancement, module [doc]

#2108 Protocol command multiplexing.
  doc/xml/release/2024/2.54.xml
  src/Makefile.in
  src/command/archive/get/get.c
  src/command/archive/get/protocol.c
  src/command/archive/get/protocol.h
  src/command/archive/push/protocol.c
  src/command/archive/push/protocol.h
  src/command/archive/push/push.c
  src/command/backup/backup.c
  src/command/backup/protocol.c
  src/command/backup/protocol.h
  src/command/remote/remote.c
  src/command/restore/protocol.c
  src/command/restore/protocol.h
  src/command/restore/restore.c
  src/command/verify/protocol.c
  src/command/verify/protocol.h
  src/command/verify/verify.c
  src/config/protocol.c
  src/config/protocol.h
  src/db/db.c
  src/db/protocol.c
  src/db/protocol.h
  src/meson.build
  src/postgres/client.c
  src/postgres/client.h
  src/protocol/client.c
  src/protocol/client.h
  src/protocol/command.c
  src/protocol/command.h
  src/protocol/helper.c
  src/protocol/parallel.c
  src/protocol/parallelJob.c
  src/protocol/parallelJob.h
  src/protocol/server.c
  src/protocol/server.h
  src/storage/remote/protocol.c
  src/storage/remote/protocol.h
  src/storage/remote/read.c
  src/storage/remote/storage.c
  src/storage/remote/write.c
  test/code-count/file-type.yaml
  test/define.yaml
  test/src/common/harnessDebug.h
  test/src/common/harnessProtocol.c
  test/src/module/command/backupTest.c
  test/src/module/db/dbTest.c
  test/src/module/postgres/clientTest.c
  test/src/module/protocol/protocolTest.c
  test/src/module/storage/remoteTest.c
Labels: module [core], enhancement

#2413 Fix typo in user guide.
  doc/xml/user-guide.xml
Labels: enhancement, module [doc]

#2399 Summarize backup reference list for info command text output.
  doc/xml/release/2024/2.54.xml
  src/build/help/help.xml
  src/command/info/info.c
  test/src/module/command/infoTest.c
Labels: module [core], enhancement
