Repository pgbackrest/pgbackrest, pull requests merged in 2024-10, with the labels that each got.

#2453 Correctly display current values for indexed options in help.
  doc/xml/release/2024/2.54.xml
  src/command/help/help.c
  test/src/module/command/helpTest.c
Labels: module [core], enhancement

#2459 Fix PostgreSQL query performance for large datasets.
  doc/xml/release/2024/2.54.xml
  doc/xml/release/contributor.xml
  src/postgres/client.c
  test/src/common/harnessPq.c
  test/src/common/harnessPq.h
  test/src/module/postgres/clientTest.c
Labels: bug, module [core]

#2439 Improve SFTP error messages.
  doc/xml/release/2024/2.54.xml
  src/storage/sftp/storage.c
  test/define.yaml
  test/src/module/storage/sftpTest.c
Labels: module [core], enhancement

#2467 Clarify source for data_directory.
  doc/xml/release/2024/2.54.xml
  doc/xml/release/contributor.xml
  doc/xml/user-guide.xml
  src/build/help/help.xml
Labels: enhancement, module [doc]

#2470 Remove autoconf/make build.
  .github/workflows/test.yml
  doc/RELEASE.md
  doc/xml/release/2025/2.55.0.xml
  doc/xml/user-guide.xml
  src/Makefile.in
  src/build.auto.h.in
  src/build/aclocal.m4
  src/build/config.guess
  src/build/config.sub
  src/build/configure.ac
  src/build/install-sh
  src/configure
  test/code-count/file-type.yaml
  test/lib/pgBackRestTest/Common/CodeCountTest.pm
  test/test.pl
Labels: module [core], enhancement

#2472 Remove support for PostgreSQL 9.4.
  CONTRIBUTING.md
  doc/xml/contributing.xml
  doc/xml/release/2025/2.55.0.xml
  src/build/help/help.xml
  src/build/postgres/postgres.yaml
  src/command/archive/common.h
  src/command/expire/expire.c
  src/command/restore/restore.c
  src/command/verify/verify.c
  src/info/infoPg.c
  src/postgres/interface.c
  src/postgres/interface/crc32.c
  src/postgres/interface/crc32.h
  src/postgres/interface/version.intern.h
  src/postgres/interface/version.vendor.h
  src/postgres/version.auto.h
  src/postgres/version.h
  test/code-count/file-type.yaml
  test/lib/pgBackRestTest/Common/DbVersion.pm
  test/lib/pgBackRestTest/Common/JobTest.pm
  test/lib/pgBackRestTest/Common/VmTest.pm
  test/src/common/harnessPostgres.c
  test/src/common/harnessPostgres.h
  test/src/common/harnessPostgres/harness094.c
  test/src/common/harnessPostgres/harnessVersion.intern.h
  test/src/module/command/archiveCommonTest.c
  test/src/module/command/archivePushTest.c
  test/src/module/command/backupTest.c
  test/src/module/command/checkTest.c
  test/src/module/command/expireTest.c
  test/src/module/command/infoTest.c
  test/src/module/command/restoreTest.c
  test/src/module/command/stanzaTest.c
  test/src/module/command/verifyTest.c
  test/src/module/db/dbTest.c
  test/src/module/info/infoArchiveTest.c
  test/src/module/info/infoBackupTest.c
  test/src/module/info/infoPgTest.c
  test/src/module/info/manifestTest.c
  test/src/module/integration/allTest.c
  test/src/module/postgres/interfaceTest.c
  test/src/module/storage/posixTest.c
  test/src/module/storage/sftpTest.c
Labels: module [core], enhancement
