Repository pgbackrest/pgbackrest, pull requests merged in 2024-03, with the labels that each got.

#2272 Skip zero-length files for block incremental delta restore.
  doc/xml/release/2024/2.51.xml
  doc/xml/release/contributor.xml
  src/command/restore/file.c
  test/src/module/command/restoreTest.c
Labels: bug, module [core]

#2276 Fix performance regression in storage list.
  doc/xml/release/2024/2.51.xml
  doc/xml/release/contributor.xml
  src/storage/storage.c
  test/src/module/storage/posixTest.c
  test/src/module/storage/sftpTest.c
Labels: bug, module [core]

#2280 Improve sort comparators.
  doc/xml/release/2024/2.51.xml
  src/command/archive/common.c
  src/command/backup/blockMap.c
  src/common/type/list.c
  src/common/type/list.h
  test/src/module/common/typeListTest.c
  test/src/module/performance/typeTest.c
Labels: module [core], enhancement

#2277 Improve archive-push WAL segment queue handling.
  doc/xml/release/2024/2.51.xml
  src/command/archive/push/push.c
  test/src/module/command/archivePushTest.c
Labels: module [core], enhancement

#2257 Detect files that have not changed during non-delta incremental backup.
  doc/xml/release/2024/2.51.xml
  src/command/backup/backup.c
  src/command/backup/blockIncr.c
  src/command/backup/file.c
  src/command/backup/file.h
  src/command/backup/protocol.c
  src/info/manifest.c
  src/info/manifest.h
  test/src/module/command/backupTest.c
  test/src/module/info/manifestTest.c
Labels: module [core], enhancement

#2268 Limit resume functionality to full backups.
  doc/xml/release/2024/2.51.xml
  src/command/backup/backup.c
  test/src/module/command/backupTest.c
Labels: module [core], enhancement

#2264 Make meson the primary build system.
  .github/workflows/test.yml
  doc/src/meson.build
  doc/xml/release/2024/2.51.xml
  doc/xml/user-guide.xml
  meson_options.txt
  test/ci.pl
  test/lib/pgBackRestTest/Common/JobTest.pm
  test/src/command/test/build.c
  test/src/meson.build
  test/src/module/test/testTest.c
  test/test.pl
Labels: module [build], enhancement

#2265 Set function/variable visibility to hidden.
  doc/xml/release/2024/2.51.xml
  src/meson.build
Labels: module [build], enhancement

#2235 Improved support for dual stack connections.
  doc/xml/release/2024/2.51.xml
  src/common/io/socket/address.c
  src/common/io/socket/address.h
  src/common/io/socket/client.c
  src/common/io/socket/common.c
  src/common/io/socket/common.h
  src/common/io/socket/server.c
  test/define.yaml
  test/src/common/harnessSocket.c
  test/src/common/harnessSocket.h
  test/src/module/common/ioHttpTest.c
  test/src/module/common/ioTlsTest.c
Labels: module [core], enhancement

#2232 Prevent invalid recovery when backup_label removed.
  doc/xml/release/2024/2.51.xml
  src/command/archive/get/get.c
  src/command/restore/restore.c
  src/postgres/interface.c
  src/postgres/interface.h
  src/postgres/interface/version.intern.h
  test/src/module/command/archiveGetTest.c
  test/src/module/command/restoreTest.c
  test/src/module/postgres/interfaceTest.c
Labels: module [core], enhancement

#2296 Update resume functionality for block incremental.
  doc/xml/release/2024/2.51.xml
  src/command/backup/backup.c
  test/src/module/command/backupTest.c
Labels: module [core], enhancement

#2304 Fix progress logging when file size changes during backup.
  doc/xml/release/2024/2.51.xml
  doc/xml/release/contributor.xml
  src/command/backup/backup.c
  test/src/module/command/backupTest.c
Labels: bug, module [core]

#2312 Tag pgbackrest build target in meson as installable.
  doc/xml/release/2024/2.52.xml
  doc/xml/release/contributor.xml
  src/meson.build
Labels: module [build], enhancement
