Repository pgbackrest/pgbackrest, pull requests merged in 2024-11, with the labels that each got.

#2477 Fix issue with version/help commands attempting to load pgbackrest.conf.
  doc/xml/release/2025/2.55.0.xml
  doc/xml/release/contributor.xml
  src/config/parse.c
  test/src/module/config/parseTest.c
Labels: bug, module [core]

#2481 Stabilize async archiving in integration tests.
  doc/xml/release/2025/2.55.0.xml
  test/src/common/harnessHost.c
Labels: enhancement, module [test]

#2493 Fix typos
  doc/lib/pgBackRestDoc/Common/DocConfig.pm
  doc/lib/pgBackRestDoc/Common/DocExecute.pm
  doc/xml/user-guide.xml
  src/command/restore/restore.c
  src/command/verify/verify.c
  src/common/memContext.h
  src/config/config.c
  src/config/parse.c
  src/info/manifest.c
  src/storage/remote/protocol.c
  src/storage/sftp/storage.c
  src/storage/storage.h
  test/lib/pgBackRestTest/Common/ContainerTest.pm
  test/src/common/harnessDebug.h
  test/src/common/harnessHost.h
  test/src/common/harnessLibSsh2.h
  test/src/common/harnessLog.c
  test/src/common/harnessProtocol.h
  test/src/common/harnessStorage.c
  test/src/module/command/backupTest.c
  test/src/module/command/restoreTest.c
  test/src/module/db/dbTest.c
  test/src/module/info/manifestTest.c
  test/src/module/performance/storageTest.c
  test/src/module/storage/sftpTest.c
Labels: module [core], enhancement

#2488 Use lz4 for protocol compression.
  doc/xml/release/2025/2.55.0.xml
  src/build/config/config.yaml
  src/config/parse.auto.c.inc
  src/storage/remote/read.c
  src/storage/remote/write.c
  test/src/module/command/helpTest.c
  test/src/module/config/parseTest.c
Labels: module [core], enhancement

#2306 Full/incremental backup method.
  doc/xml/release/2025/2.55.0.xml
  src/build/config/config.yaml
  src/build/help/help.xml
  src/command/backup/backup.c
  src/command/backup/file.c
  src/common/time.h
  src/config/config.auto.h
  src/config/parse.auto.c.inc
  src/db/db.c
  src/info/manifest.c
  src/info/manifest.h
  src/postgres/interface.h
  src/postgres/interface/version.intern.h
  test/src/common/harnessBackup.c
  test/src/common/harnessBackup.h
  test/src/common/harnessHost.c
  test/src/common/harnessHost.h
  test/src/common/harnessLog.c
  test/src/common/harnessLog.h
  test/src/common/harnessPostgres/harnessVersion.intern.h
  test/src/common/harnessPq.h
  test/src/module/command/backupTest.c
  test/src/module/command/manifestTest.c
  test/src/module/info/manifestTest.c
  test/src/module/integration/allTest.c
  test/src/module/postgres/interfaceTest.c
Labels: module [core], enhancement
