Repository pgbackrest/pgbackrest, pull requests merged in 2025-04, with the labels that each got.

#2588 Revert "full/incremental backup method".
  doc/xml/release/2025/2.55.0.xml
  src/build/config/config.yaml
  src/build/help/help.xml
  src/command/backup/backup.c
  src/command/backup/file.c
  src/common/time.h
  src/config/config.auto.h
  src/config/parse.auto.c.inc
  src/info/manifest.c
  src/info/manifest.h
  src/postgres/interface.h
  src/postgres/interface/version.intern.h
  test/src/common/harnessBackup.c
  test/src/common/harnessBackup.h
  test/src/common/harnessHost.c
  test/src/common/harnessHost.h
  test/src/common/harnessPostgres/harnessVersion.intern.h
  test/src/module/command/backupTest.c
  test/src/module/command/manifestTest.c
  test/src/module/info/manifestTest.c
  test/src/module/integration/allTest.c
  test/src/module/postgres/interfaceTest.c
Labels: module [core], enhancement

#2595 Fix documentation for specifying multiple stanzas with tls-server-auth.
  doc/xml/release/2025/2.55.0.xml
  doc/xml/release/contributor.xml
  src/build/help/help.xml
  src/protocol/helper.c
  test/src/module/command/serverTest.c
Labels: bug, module [doc]

#2592 Calculate content-md5 on S3 only when required.
  doc/xml/release/2025/2.55.0.xml
  src/storage/s3/storage.c
  src/storage/s3/storage.intern.h
  test/src/module/storage/s3Test.c
Labels: module [core], enhancement

#2535 Allow connections to PostgreSQL on abstract domain sockets.
  doc/xml/release/2025/2.55.0.xml
  src/build/config/config.yaml
  src/config/parse.auto.c.inc
  test/src/module/config/parseTest.c
Labels: module [core], enhancement

#2594 Warn when a value for a multi-key option is overwritten.
  doc/xml/release/2025/2.55.0.xml
  src/config/parse.c
  test/src/module/config/parseTest.c
Labels: module [core], enhancement

#2603 PostgreSQL 18 experimental support.
  doc/xml/release/2025/2.55.0.xml
  src/build/postgres/postgres.yaml
  src/postgres/interface/version.vendor.h
  src/postgres/version.auto.h
  test/container.yaml
  test/lib/pgBackRestTest/Common/ContainerTest.pm
  test/lib/pgBackRestTest/Common/DbVersion.pm
  test/lib/pgBackRestTest/Common/VmTest.pm
  test/src/common/harnessPostgres.c
  test/src/common/harnessPostgres.h
  test/src/common/harnessPostgres/harness180.c
  test/src/module/integration/allTest.c
  test/src/module/postgres/interfaceTest.c
Labels: module [core], enhancement

#2601 Clarify incremental backup expiration.
  doc/xml/release/2025/2.55.0.xml
  doc/xml/user-guide.xml
  src/build/help/help.xml
Labels: enhancement, module [doc]

#2608 Fix incorrect not-equal comparison in TEST_RESULT_Z_NE().
  doc/xml/release/2025/2.55.0.xml
  test/src/common/harnessTest.c
Labels: bug, module [test]

#2611 Fix lower bounds checking for option keys.
  doc/xml/release/2025/2.56.0.xml
  doc/xml/release/contributor.xml
  src/config/parse.c
  test/src/module/config/parseTest.c
Labels: bug, module [core]

#2615 Revert "calculate content-md5 on S3 only when required".
  doc/resource/git-history.cache
  doc/xml/release/2025/2.56.0.xml
  doc/xml/release/contributor.xml
  src/storage/s3/storage.c
  src/storage/s3/storage.intern.h
  test/src/module/storage/s3Test.c
Labels: bug, module [core]
